# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem, QMessageBox, QInputDialog
from PyQt5.QtCore import Qt
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        # Таблица
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 1160, 580))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        
        # Простые кнопки внизу
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 620, 120, 30))
        self.pushButton.setObjectName("pushButton")
        
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(180, 620, 120, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(310, 620, 120, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(440, 620, 120, 30))
        self.pushButton_4.setObjectName("pushButton_4")
        
        # Кнопка выхода в правом верхнем углу
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(1080, 620, 100, 30))
        self.pushButton_5.setObjectName("pushButton_5")
        
        MainWindow.setCentralWidget(self.centralwidget)
        
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # Подключение сигналов
        self.pushButton.clicked.connect(self.add_row)
        self.pushButton_2.clicked.connect(self.edit_row)
        self.pushButton_3.clicked.connect(self.delete_row)
        self.pushButton_4.clicked.connect(self.update_table)
        self.pushButton_5.clicked.connect(self.close)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.loaddb()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "БД"))
        self.pushButton.setText(_translate("MainWindow", "Добавить"))
        self.pushButton_2.setText(_translate("MainWindow", "Изменить"))
        self.pushButton_3.setText(_translate("MainWindow", "Удалить"))
        self.pushButton_4.setText(_translate("MainWindow", "Обновить"))
        self.pushButton_5.setText(_translate("MainWindow", "Выход"))

    def add_row(self):
        connection = sqlite3.connect('my_db.db')
        cursor = connection.cursor()
        cursor.execute('PRAGMA table_info(Users)')
        columns_info = cursor.fetchall()
        
        column_names = ', '.join([col[1] for col in columns_info])
        
        text, ok = QInputDialog.getText(None, "Добавить запись", 
                                       f"Столбцы: {column_names}\nВведите значения через запятую:")
        if ok and text:
            values = [v.strip() for v in text.split(',')]
        
            placeholders = ', '.join(['?' for _ in values])
            query = f"INSERT INTO Users VALUES ({placeholders})"
            
            try:
                cursor.execute(query, values)
                connection.commit()
            except Exception as e:
                QMessageBox.warning(None, "Ошибка", str(e))
            
            cursor.close()
            connection.close()
            self.loaddb()

    def edit_row(self):
        selection = self.tableWidget.currentRow()
        if selection < 0:
            QMessageBox.warning(None, "Ошибка", "Выберите запись!")
            return
            
        connection = sqlite3.connect('my_db.db')
        cursor = connection.cursor()
        
        id_item = self.tableWidget.item(selection, 0)
        record_id = id_item.text()

        current_values = []
        for col in range(self.tableWidget.columnCount()):
            item = self.tableWidget.item(selection, col)
            current_values.append(item.text() if item else "")

        cursor.execute('PRAGMA table_info(Users)')
        columns_info = cursor.fetchall()
        column_names = [col[1] for col in columns_info]
        
        text, ok = QInputDialog.getText(
            None,
            "Изменить запись",
            f"Столбцы: {', '.join(column_names)}\n"
            f"Текущие: {', '.join(current_values)}\n"
            f"Новые значения через запятую:",
            text=', '.join(current_values)
        )

        if ok and text:
            new_values = [v.strip() for v in text.split(',')]
            
            set_clause = ', '.join([f"{col} = ?" for col in column_names[1:]])
            query = f"UPDATE Users SET {set_clause} WHERE {column_names[0]} = ?"
            
            try:
                cursor.execute(query, new_values[1:] + [record_id])
                connection.commit()
            except Exception as e:
                QMessageBox.warning(None, "Ошибка", str(e))
            
            connection.close()
            self.loaddb()

    def delete_row(self):
        selection = self.tableWidget.currentRow()
        if selection < 0:
            QMessageBox.warning(None, "Ошибка", "Выберите запись!")
            return
            
        reply = QMessageBox.question(None, "Подтверждение", 
                                    "Удалить запись?",
                                    QMessageBox.Yes | QMessageBox.No)
        
        if reply == QMessageBox.Yes:
            connection = sqlite3.connect('my_db.db')
            cursor = connection.cursor()
            id_item = self.tableWidget.item(selection, 0)
            record_id = id_item.text()
            
            try:
                cursor.execute("DELETE FROM Users WHERE id = ?", (record_id,))
                connection.commit()
            except Exception as e:
                QMessageBox.warning(None, "Ошибка", str(e))
            
            connection.close()
            self.loaddb()

    def update_table(self):
        self.loaddb()

    def loaddb(self):
        connection = sqlite3.connect('my_db.db')
        cursor = connection.cursor()

        try:
            cursor.execute('SELECT * FROM Users')
            data = cursor.fetchall()

            cursor.execute('PRAGMA table_info(Users)')
            columns = [col[1] for col in cursor.fetchall()]

            self.tableWidget.setColumnCount(len(columns))
            self.tableWidget.setHorizontalHeaderLabels(columns)
            self.tableWidget.setRowCount(len(data))

            for row_idx, row in enumerate(data):
                for col_idx, value in enumerate(row):
                    self.tableWidget.setItem(row_idx, col_idx, QTableWidgetItem(str(value)))
            
            self.tableWidget.resizeColumnsToContents()
            
        except Exception as e:
            QMessageBox.warning(None, "Ошибка", str(e))
        finally:
            connection.close()

    def close(self, event):
        reply = QMessageBox.question(None, "Выход", "Выйти?",
                                    QMessageBox.Yes | QMessageBox.No)
        if reply == QMessageBox.Yes:
            event.accept()
        else:
            event.ignore()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
